apiVersion: v1
kind: ConfigMap
metadata:
  name: chain-config
  namespace: hyperlane-agents
data:
  GORCHAIN_RPC_URL: "${GORCHAIN_RPC_URL}"
  SOLANA_RPC_URL: "${SOLANA_RPC_URL}"
  GORCHAIN_DOMAIN_ID: "${GORCHAIN_DOMAIN_ID}"
  SOLANA_DOMAIN_ID: "${SOLANA_DOMAIN_ID}"
  GORCHAIN_IGP_PROGRAM_ID: "${GORCHAIN_IGP_PROGRAM_ID}"
  SOLANA_IGP_PROGRAM_ID: "${SOLANA_IGP_PROGRAM_ID}"
