{
  "tokens": [
    {
      "chainName": "solana",
      "standard": "SealevelHypCollateral",
      "name": "USD Coin",
      "symbol": "USDC",
      "decimals": 6,
      "addressOrDenom": "GNFKJ6ZS1MweqxF543N1Cv7aPBuCdBNiWi3xWengabgr",
      "mailbox": "BPKU1hMJLED7DriqLePXCeW4Uv6cF1zHeE49RYJwpttG",
      "connections": [
        {
          "token": "sealevel|gorchain|9WR3An5HjR9HEsYhAiR17jyvgoevrzzDsR1u8WnjusXQ"
        }
      ],
      "collateralAddressOrDenom": "EDEappBGxV8nMRMMcng4DUUH5dUF2ZFiRubS7V9NYF9d",
      "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png"
    },
    {
      "chainName": "gorchain",
      "standard": "SealevelHypSynthetic",
      "name": "USD Coin",
      "symbol": "USDC",
      "decimals": 6,
      "addressOrDenom": "9WR3An5HjR9HEsYhAiR17jyvgoevrzzDsR1u8WnjusXQ",
      "mailbox": "4Fi8JUYanzpfaD9nc9DdNVDR1fc6QtNyRUX7TJmwbtER",
      "connections": [
        {
          "token": "sealevel|solana|GNFKJ6ZS1MweqxF543N1Cv7aPBuCdBNiWi3xWengabgr"
        }
      ],
      "collateralAddressOrDenom": "CVNq8NG9XmqmsyCJEUgwLv6W2ESjKFRMUDcsjjWWWStG",
      "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png"
    }
  ],
  "options": {}
}
