{
  "tokens": [
    {
      "chainName": "solana",
      "standard": "SealevelHypCollateral",
      "name": "USD Coin",
      "symbol": "USDC",
      "decimals": 6,
      "addressOrDenom": "2uF65F3ApKdVKVdmRgBHpLErbnAeBw3MZSNb4ZbAvED1",
      "mailbox": "A63TnNPUmBcSgQnSQU1JqJ6bVk8kuwbzKAscwo3mfqmt",
      "connections": [
        {
          "token": "sealevel|gorchain|7KSSNs2BgCSYPjWRT27rCjNyLiXF7WadQDGsqYoUMZXg"
        }
      ],
      "collateralAddressOrDenom": "5YCHEf1Rsnoz3fGMHAiHANiaVT28tAMcYRcCK3wV8TTp"
    },
    {
      "chainName": "gorchain",
      "standard": "SealevelHypSynthetic",
      "name": "USD Coin",
      "symbol": "USDC",
      "decimals": 6,
      "addressOrDenom": "7KSSNs2BgCSYPjWRT27rCjNyLiXF7WadQDGsqYoUMZXg",
      "mailbox": "CefC91Km86uYtjhJHis5JCuo4Q6fmWXoorLG9vm7y2W",
      "connections": [
        {
          "token": "sealevel|solana|2uF65F3ApKdVKVdmRgBHpLErbnAeBw3MZSNb4ZbAvED1"
        }
      ],
      "collateralAddressOrDenom": "H4b1spC4musrm6o8dChdnYybKdYRz1gaDyPMj7sZBBHf"
    }
  ],
  "options": {}
}
