---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_connection: local
    deployer_hosts:
      hosts:
        bridge-host-1:
    minio_hosts:
      hosts:
        bridge-host-1:
    relayer_hosts:
      hosts:
        bridge-host-1:
    gas_oracle_hosts:
      hosts:
        bridge-host-1:
    monitoring_hosts:
      hosts:
        bridge-host-1:
    warp_ui_hosts:
      hosts:
        bridge-host-1:
