apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hyperlane-svm-ops

resources:
  - kill-switch-job.yaml
  - restore-job.yaml
  - teardown-job.yaml
  - verify-ownership-job.yaml
