---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_connection: local
    deployer_hosts:
      hosts:
        staging-bridge-ops:
    minio_hosts:
      hosts:
        staging-bridge-ops:
    relayer_hosts:
      hosts:
        staging-bridge-ops:
    gas_oracle_hosts:
      hosts:
        staging-bridge-ops:
    monitoring_hosts:
      hosts:
        staging-bridge-ops:
    warp_ui_hosts:
      hosts:
        staging-bridge-ops:
    chain_hosts:
      hosts:
        staging-gorchain:
        staging-solana-validator:
