{
 "title": "Hyperlane Relayer",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hyperlane_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"relayers\"}, hyperlane_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages Processed",
   "type": "timeseries",
   "description": "There shouldn't be abrupt changes, especially for a specific pair",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (origin,remote,hyperlane_instance)(round(increase(hyperlane_messages_processed_count{hyperlane_instance=~\"${hyperlane_instance:regex}\"}[5m])))",
     "legendFormat": "{{origin}}->{{remote}}"
    }
   ]
  },
  {
   "title": "Prepare queues (all)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (remote, queue_name, hyperlane_instance)(\n    hyperlane_submitter_queue_length{queue_name=\"prepare_queue\", hyperlane_instance=~\"${hyperlane_instance:regex}\"}\n)",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "Submit Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(remote, queue_name, hyperlane_instance) (hyperlane_submitter_queue_length{queue_name=\"submit_queue\", hyperlane_instance=~\"${hyperlane_instance:regex}\"})",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "Confirm Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(remote, queue_name, hyperlane_instance) (avg_over_time(hyperlane_submitter_queue_length{queue_name=\"confirm_queue\", hyperlane_instance=~\"${hyperlane_instance:regex}\"}[20m]))",
     "legendFormat": "{{remote}}"
    }
   ]
  }
 ]
}